[package]
name = "hydrogen-music"
version = "0.8.0"
description = "A local-first music player"
authors = ["xleave"]
edition = "2021"

[lib]
name = "hydrogen_music_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
lofty = "0.24"
rayon = "1"
rodio = { version = "0.22.2", features = ["symphonia-all"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"

[target.'cfg(all(not(any(target_os = "android", target_os = "ios")), not(target_os = "linux")))'.dependencies]
tauri-plugin-global-shortcut = "2"

[target.'cfg(target_os = "linux")'.dependencies]
souvlaki = { version = "0.8.3", default-features = false, features = ["use_zbus"] }
wayclip-global-hotkey = "0.7.0"
